//! Domain models for the entity graph and knowledge corpus.

use chrono::{DateTime, Utc};
use macro_uuid::Uuid;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

/// Result alias.
pub type Result<T> = std::result::Result<T, GraphError>;

/// SHA-256 hex of document body.
pub fn content_hash(body: &str) -> String {
    hex::encode(Sha256::digest(body.as_bytes()))
}

/// A typed graph node.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct GraphNode {
    /// Node id.
    pub id: Uuid,
    /// Owning organization.
    pub org_id: Option<i32>,
    /// schema.org-inspired type (`Person`, `Device`, `SoftwareApplication`).
    pub node_type: String,
    /// Display name.
    pub display_name: String,
    /// Attributes blob.
    pub attributes: serde_json::Value,
    /// Optional native Macro entity type.
    pub native_entity_type: Option<String>,
    /// Optional native Macro entity id.
    pub native_entity_id: Option<String>,
    /// Created at.
    pub created_at: DateTime<Utc>,
    /// Updated at.
    pub updated_at: DateTime<Utc>,
}

/// A typed relationship between two nodes.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct GraphEdge {
    /// Edge id.
    pub id: Uuid,
    /// Owning organization.
    pub org_id: Option<i32>,
    /// Source node.
    pub from_node_id: Uuid,
    /// Target node.
    pub to_node_id: Uuid,
    /// Relationship type (`employs`, `owns_device`, `has_account`).
    pub relationship: String,
    /// Attributes blob.
    pub attributes: serde_json::Value,
    /// Created at.
    pub created_at: DateTime<Utc>,
}

/// An OKF-style knowledge document.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct KnowledgeDocument {
    /// Document id.
    pub id: Uuid,
    /// Owning organization.
    pub org_id: Option<i32>,
    /// Slug.
    pub slug: String,
    /// Title.
    pub title: String,
    /// Markdown body.
    pub body: String,
    /// OKF type.
    pub okf_type: String,
    /// Sources.
    pub okf_sources: Vec<String>,
    /// Generated by an agent.
    pub okf_generated: bool,
    /// Verified by a human.
    pub okf_verified: bool,
    /// `draft` | `active` | `deprecated` | `archived`.
    pub okf_status: String,
    /// Stale-after timestamp.
    pub stale_after: Option<DateTime<Utc>>,
    /// Content hash.
    pub content_hash: String,
    /// Human-authored documents are never overwritten by generated updates.
    pub human_authored: bool,
    /// Created at.
    pub created_at: DateTime<Utc>,
    /// Updated at.
    pub updated_at: DateTime<Utc>,
}

/// Fields to upsert a node.
#[derive(Debug, Clone)]
pub struct UpsertNode {
    /// Node type.
    pub node_type: String,
    /// Display name.
    pub display_name: String,
    /// Attributes.
    pub attributes: serde_json::Value,
    /// Native entity type.
    pub native_entity_type: Option<String>,
    /// Native entity id.
    pub native_entity_id: Option<String>,
}

/// Fields to upsert an edge.
#[derive(Debug, Clone)]
pub struct UpsertEdge {
    /// Source.
    pub from_node_id: Uuid,
    /// Target.
    pub to_node_id: Uuid,
    /// Relationship.
    pub relationship: String,
    /// Attributes.
    pub attributes: serde_json::Value,
}

/// Fields to upsert a knowledge document.
#[derive(Debug, Clone)]
pub struct UpsertKnowledge {
    /// Slug.
    pub slug: String,
    /// Title.
    pub title: String,
    /// Body.
    pub body: String,
    /// Sources.
    pub okf_sources: Vec<String>,
    /// Generated flag.
    pub okf_generated: bool,
    /// Human-authored flag. Once true, generated upserts are refused.
    pub human_authored: bool,
}

/// Graph errors.
#[derive(Debug, thiserror::Error)]
pub enum GraphError {
    /// Invalid request.
    #[error("{0}")]
    InvalidRequest(String),
    /// Not found / tenancy miss.
    #[error("not found")]
    NotFound,
    /// Refused to overwrite a human-authored document.
    #[error("human-authored knowledge cannot be overwritten")]
    HumanAuthoredProtected,
    /// Missing agent scope.
    #[error("missing required scope: {required}")]
    MissingScope {
        /// Required scope.
        required: String,
    },
    /// Database failure.
    #[error(transparent)]
    Database(#[from] sqlx::Error),
}
